### ISSUE TITLE
 results are not giving the cheapest product from each website

### ISSUE THREAD

**Issue by sumalatha-99** [EZ7051/cheapBuy#6]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by soubhagya31** [comment]
Th url fetches product results from the website with only the product description. The first result is being displayed as the cheapest product. It is not guaranteed that the first result is the cheapest product
![image](https://github.com/EZ7051/cheapBuy/assets/143368827/9c61b666-9d84-4d9d-8ea2-bce9e51a577a)
![image](https://github.com/EZ7051/cheapBuy/assets/143368827/75c9814a-ffb3-4973-bd97-0d11df9f14e4)

**Comment by soubhagya31** [comment]
Solved the issue by adding filter parameters to the url.. Thus we fetched the results in the lowest to highest sorted order and displayed the first result. Thus resolved the issue.

![image](https://github.com/EZ7051/cheapBuy/assets/143368827/b1448414-092e-4ebc-b571-9bf36ae805f0)

**Comment by soubhagya31** [comment]
Hence, closing the issue
